add_newline = false
format = """$aws$docker_context$directory$character"""

[aws]
symbol = "îŒ½ "
style = "bold yellow"
format = "[$symbol($profile)]($style) "

[docker_context]
symbol = "ïŒˆ "
style = "bold blue"
format = "[$symbol($context)]($style) "

[directory]
style = "bold white"
read_only = " ðŸ”’"

[character]
success_symbol = "[âžœ](bold green)"